#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the catAndMouse function below.
def catAndMouse(x, y, z):
    s1=int(x-z)
    s2=int(y-z)
    if s1<0:
        s1=0-s1
    if s2<0:
        s2=0-s2
    if s1>s2:
        return ("Cat B")
    elif s2>s1:
        return ("Cat A")
    elif s1==s2:
        return ("Mouse C")

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        xyz = input().split()

        x = int(xyz[0])

        y = int(xyz[1])

        z = int(xyz[2])

        result = catAndMouse(x, y, z)

        fptr.write(result + '\n')

    fptr.close()
