#!/bin/python3

import sys

def lowestTriangle(base, area):
    # Complete this function
     h=2*(area/base)
     if (area%base)==0:
        return int(h)
     else:
        h=int(h)+1
        return h

base, area = input().strip().split(' ')
base, area = [int(base), int(area)]
height = lowestTriangle(base, area)
print(height)

